const LARAVEL_BOOST_CONFIG = "laravel_boost";
const LARAVEL_CUSTOM_STARTER_CONFIG = "laravel_custom_starter";
const LARAVEL_DATABASE_RUNTIME_CONFIG = "laravel_database_runtime";
const LARAVEL_PACKAGE_MANAGER_CONFIG = "laravel_package_manager";
const LARAVEL_PROJECT_KNOWLEDGE_RELATIVE_PATH = ".ai-studio/LARAVEL_PROJECT.md";
const LARAVEL_STARTER_KIT_CONFIG = "laravel_starter_kit";
const LARAVEL_TESTING_CONFIG = "laravel_testing";

export {
  LARAVEL_BOOST_CONFIG,
  LARAVEL_CUSTOM_STARTER_CONFIG,
  LARAVEL_DATABASE_RUNTIME_CONFIG,
  LARAVEL_PACKAGE_MANAGER_CONFIG,
  LARAVEL_PROJECT_KNOWLEDGE_RELATIVE_PATH,
  LARAVEL_STARTER_KIT_CONFIG,
  LARAVEL_TESTING_CONFIG
};
